# Usa variables de entorno, con fallback a los datos locales
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/videogames_store}
spring.datasource.username=${DB_USERNAME:santiago_dev}
spring.datasource.password=${DB_PASSWORD:password123}
spring.datasource.driver-class-name=org.postgresql.Driver

# 1. Se apaga la autocreación de tablas de Hibernate, para que no interfiera con schema.sql
spring.jpa.hibernate.ddl-auto=update

# 2. Le decimos a Spring que ejecute el schema.sql siempre al arrancar
spring.sql.init.mode=never

spring.jpa.show-sql=true